# Generated by Django 5.0.4 on 2024-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_services_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='services',
            name='image2',
            field=models.FileField(default='default.jpeg', upload_to='images'),
        ),
    ]
