# Generated by Django 5.0.4 on 2024-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_image_services_image1_services_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUpload', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpeg', upload_to='images')),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
