# Generated by Django 5.0.4 on 2024-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dateUpdated',
        ),
        migrations.AlterField(
            model_name='post',
            name='dateUpload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
