# Generated by Django 5.0.4 on 2024-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_post_dateupdated_alter_post_dateupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=200)),
                ('timeActiveNormalDays', models.CharField(max_length=100)),
                ('timeActiveWeekends', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='logo.png', upload_to='images')),
                ('linkedln', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('officeLocation', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
