# Generated by Django 5.0.4 on 2024-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('completeStatus', models.BooleanField()),
                ('image', models.ImageField(default='default.jpeg', upload_to='images')),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
