# Generated by Django 5.0.4 on 2024-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default.jpeg', upload_to='images')),
                ('statusDescription', models.TextField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
