# Generated by Django 5.0.4 on 2024-05-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_post_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='about_us_description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='about_us_image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='who_we_are_description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='who_we_are_image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
